[package]
name = "data_bender"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.15.3"
fundsp = "0.16.0"
image = { version = "0.25.0", features = ["tiff"] }
rand = "0.8.5"
